### ISSUE TITLE
Display bundle size on the repo

### ISSUE THREAD

**Issue by PuruVJ** [marvinhagemeister/smoldash#11]
This project looks awesome, and I can't wait to use it for myself.

I got one Suggestion: **Display this library's bundle size, along with lodash's**. Just reading the word `lightweight` lodash didn't tell how lightweight, so a one line size comparison would be great 🙂

![image](https://user-images.githubusercontent.com/47742487/126860427-359c628a-a846-4f71-9712-ead51a42f3f6.png)

If you're onboard, I'll be ready to make a PR putting the bundle size badge and comparison here 😁

**Comment by marvinhagemeister** [comment]
That's a great idea👍
